name = "RubberBearings"
uuid = "f6d63759-cb19-4b1b-a39a-2ff3b10d45bd"
authors = ["Eduardo J. Montalto"]
version = "1.0.0-DEV"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
